---
- name: setup arch linux
  hosts: localhost
  connection: local
  roles:
    - check_internet
    - boot_method
    - disks
    - common
    - bootloader
    - users
    - aur
    - services
    - finish
