---
# tasks file for check_internet
- name: ping archlinux.org
  command: ping archlinux.org -c 3
  register: ping_arch

- name: check if the ping failed
  debug:
    var: ping_arch.stdout_lines
  failed_when: ping_arch.rc > 1
