---
# inline hack using string to change from vault unicode to string
- name: change root password
  command: arch-chroot /mnt echo "root:{{ system.root_password | string | hash_password }}" chpasswd -e
  no_log: true

- name: add sudo group
  command: arch-chroot /mnt groupadd sudo

- name: set user fact
  set_fact:
    user: "{{ system.username }}"

- name: add user "{{ user }}"
  command: arch-chroot /mnt useradd -m -U -p "{{ system.user_password | string | hash_password }}" "{{ user }}"


