---
- name: re-run setup and gather hardware
  setup:
    gather_subset: hardware

- name: regenerate initramfs
  shell: arch-chroot /mnt mkinitcpio -P

- name: install boot loader
  shell: arch-chroot /mnt bootctl install

- name: create /boot/loader/loader.conf
  template:
    src: loader.j2
    dest: /mnt/boot/loader/loader.conf

- name: create /boot/loader/entries/arch.conf
  template:
    src: archloader.j2
    dest: /mnt/boot/loader/entries/arch.conf
